# Generated by Django 5.0 on 2024-03-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='imageurl',
            field=models.ImageField(default='abc.jpg', upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
